# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import fileupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_auto_20170603_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(upload_to=fileupload.models.get_upload_path),
        ),
    ]
