# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
