# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170721_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_time',
            field=models.DateTimeField(),
        ),
    ]
