# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170213_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('publish_time', 'text', 'author')},
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='blog',
            field=models.ManyToManyField(to='blogs.Blog'),
        ),
    ]
