# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170213_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-publish_time', 'title', 'author')},
        ),
    ]
