# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20170721_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
