# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blogdraft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogdraft',
            options={'ordering': ('author',)},
        ),
    ]
