# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170817_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
