# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='star',
        ),
        migrations.AddField(
            model_name='follow',
            name='stars',
            field=models.ManyToManyField(to='accounts.Follow'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
