# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170818_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Reply', 'Reply'), ('At', 'At')], default='Reply', max_length=5),
            preserve_default=False,
        ),
    ]
