# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Reply', 'Reply'), ('Subscribe', 'Subscribe'), ('At', 'At')], max_length=9),
        ),
    ]
